<!-- catalog-support -->
<div class="catalog-support">
    <div class="text">
        <h3 class="big-text">Can’t find what your looking for?</h3>
        <span class="small-text">Our experts can help!</span>
    </div>
    <div class="links-support">
        <div class="call"><i class="fa-solid fa-phone-flip">&nbsp;</i>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="call us" title="call us" template="widget/link/link_block.phtml" page_id="1"}}</div>
        <div class="chat"><i class="fa-solid fa-message">&nbsp;</i>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="chat now" title="chat now" template="widget/link/link_block.phtml" page_id="1"}}</div>
    </div>
</div>