<!-- header-top -->
<div class="header-top">
    <ul class="top-links">
        <li class="links"><a href="#"><i class="fa-solid fa-phone-flip">&nbsp;</i>1300 000 000</a></li>
        <li class="links">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Help/FAQ" title="Help/FAQ" template="widget/link/link_block.phtml" page_id="6"}}</li>
        <li class="links">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="E-Business" title="E-Business" template="widget/link/link_block.phtml" page_id="1"}}</li>
        <li class="links">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Locations" title="Locations" template="widget/link/link_block.phtml" page_id="1"}}</li>
    </ul>
</div>

<!-- header-middle-link -->
<ul class="links-icon">
    <li><img src="{{media url="wysiwyg/homepage/header-nav-icon/solution-icon@2x.png"}}" alt="icon">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Solutions" title="Solutions" template="widget/link/link_inline.phtml" page_id="1"}}</li>
</ul>
<ul class="links-icon">
    <li><img src="{{media url="wysiwyg/homepage/header-nav-icon/lightblue-h@2x.png"}}" alt="icon">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Business Hub" title="Business Hub" template="widget/link/link_inline.phtml" page_id="1"}}</li>
</ul>

<!-- navigation-home-link -->
<p>{{widget type="Magento\Cms\Block\Widget\Page\Link" template="widget/link/link_inline.phtml" page_id="2"}}</p>

<!-- subscribe-title -->
<div class="title-list">
    <h4 class="title">Subscribe to our newsletter</h4>
    <p class="list">Keep me up to date on the latest products, inspiration and more.</p>
</div>

<!-- help-title -->
<div class="support">
    <div class="title-list">
        <h4 class="title">Help & Support</h4>
        <p class="list">Contact our team or browse our frequently asked questions.</p>
    </div>
    <div class="support-btn action primary">
    </div>
</div>

<!-- footer-links-desktop-->
<div class="footer-links-desktop">
    <div class="row">
        <div class="col-5">
            <div class="footer-links">
                <div class="title">Heatleys</div>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Company Profile" title="Company Profile" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Group Profile" title="Group Profile" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Services" title="Services" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Locations" title="Locations" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Employment" title="Employment" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-5">
            <div class="footer-links">
                <div class="title">Customer Care</div>
                <ul class="nav-link">
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Help & Support" title="Help & Support" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Returns" title="Returns" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Shipping info" title="Shipping info" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Contact us" title="Contact us" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Ordering" title="Ordering" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-5">
            <div class="footer-links">
                <div class="title">Service & Solutions</div>
                <ul class="nav-link">
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Uvex" title="Uvex" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Bailey Ladders" title="Bailey Ladders" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Sutton Tools" title="Sutton Tools" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Sika" title="Sika" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Scott Safety" title="Scott Safety" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Ryobi" title="Ryobi" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Makita" title="Makita" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Darex" title="Darex" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-5">
            <div class="footer-links">
                <div class="title">Account</div>
                <ul class="nav-link">
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Track Orders" title="Track Orders" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Login/Register" title="Login/Register" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                    <li>
                        {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Trade Login" title="Trade Login" template="widget/link/link_inline.phtml" page_id="1"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-5">
            <div class="footer-links">
                <div class="title">Contact us</div>
                <ul class="nav-link">
                    <li>
                        <div class="address">
                            <a href="#">Address: 50 Vinnicombe Drive <br>
                                Canning Vale, WA Australia 6155</a>
                        </div>
                    </li>
                    <li>
                        <div class="tel">
                            <a href="#">Tel: (08) 9256 5200</a>
                        </div>
                    </li>
                    <li>
                        <div class="fax">
                            <a href="#">Fax: (08) 9256 5222</a>
                        </div>
                    </li>
                    <li>
                        <div class="email">
                            <a href="#">Email: sales@heatleys.com.au</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- footer-links mobile-->
<div id="accordion" class="footer-links-mobile">
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="title">Heatleys</div>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Company Profile" title="Company Profile" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Group Profile" title="Group Profile" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Services" title="Services" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Locations" title="Locations" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Employment" title="Employment" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="title">Customer Care</div>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Help & Support" title="Help & Support" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Returns" title="Returns" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Shipping info" title="Shipping info" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Contact us" title="Contact us" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Ordering" title="Ordering" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="title">Service & Solutions</div>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Uvex" title="Uvex" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Bailey Ladders" title="Bailey Ladders" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Sutton Tools" title="Sutton Tools" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Sika" title="Sika" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Scott Safety" title="Scott Safety" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Ryobi" title="Ryobi" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Makita" title="Makita" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Darex" title="Darex" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="title">Account</div>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Track Orders" title="Track Orders" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Login/Register" title="Login/Register" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
            <li>
                {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Trade Login" title="Trade Login" template="widget/link/link_inline.phtml" page_id="1"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="title">Contact us</div>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>
                <div class="address">
                    <a href="#">Address: 50 Vinnicombe Drive <br>
                        Canning Vale, WA Australia 6155</a>
                </div>
            </li>
            <li>
                <div class="tel">
                    <a href="#">Tel: (08) 9256 5200</a>
                </div>
            </li>
            <li>
                <div class="fax">
                    <a href="#">Fax: (08) 9256 5222</a>
                </div>
            </li>
            <li>
                <div class="email">
                    <a href="#">Email: sales@heatleys.com.au</a>
                </div>
            </li>
        </ul>
    </div>
</div>

<!-- img-icon-footer -->
<div class="link-icon">
    <div class="item">
        <a href="#" class="icon-facebook"></a>
    </div>
    <div class="item">
        <a href="#" class="icon-linkedin"></a>
    </div>
    <div class="item">
        <a href="#" class="icon-youtobe"></a>
    </div>
</div>