<!-- banner_rbt -->
<div class="banner-rbt" id="banner-rbt">
    <div class="item-rbt">
        <div class="online">
            {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Online" title="Online" template="widget/link/link_inline.phtml" page_id="1"}}
        </div>
    </div>
    <div class="item-rbt">
        <div class="in-store">
            {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="In Store" title="In Store" template="widget/link/link_inline.phtml" page_id="1"}}
        </div>
    </div>
    <div class="item-rbt">
        <div class="on-site">
            {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="On Site" title="On Site" template="widget/link/link_inline.phtml" page_id="1"}}
        </div>
    </div>
    <div class="item-rbt">
        <div class="delivery">
            {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Delivery" title="Delivery" template="widget/link/link_inline.phtml" page_id="1"}}
        </div>
    </div>
    <div class="item-rbt">
        <div class="click-collect">
            {{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Click & Collect" title="Click & Collect" template="widget/link/link_inline.phtml" page_id="1"}}
        </div>
    </div>
</div>

<!-- banner -->
<div id="banner" class="banner">
    <div class="banner-item">
        <div class="banner-image"><img src="{{media url="wysiwyg/homepage/banner/banner-image.jpg"}}" alt=""></div>
        <div class="banner-text">
            <div class="content-text">
                <div class="logo-banner"><img src="{{media url="wysiwyg/homepage/logo/h-logo-white_2x.png"}}" alt=""></div>
                <div class="big-text">
                    <h3>Product<br>Spotlight</h3>
                </div>
                <div class="small-text">The latest tool release<br>from Milwaukie</div>
                <span class="shop-btn">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Shop now" title="Shop now" template="widget/link/link_inline.phtml" page_id="1"}}</span>
            </div>
        </div>
    </div>
</div>

<!-- blog_heatleys -->
<div id="blog-heatleys" class="blog">
    <div class="row">
        <div class="col-3">
            <div class="blog-item">
                <div class="blog-image"><img src="{{media url="wysiwyg/homepage/main_homepage/blog/homepage-retail-14.jpg"}}" alt=""></div>
                <div class="blog-content">
                    <div class="blog-name">
                        <h4>Services &amp; Solutions</h4>
                    </div>
                    <div class="content">
                        <p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum.</p>
                    </div>
                    <div class="blog-link">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Learn more" title="Learn more" template="widget/link/link_inline.phtml" page_id="1"}}</div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="blog-item">
                <div class="blog-image"><img src="{{media url="wysiwyg/homepage/main_homepage/blog/homepage-retail-13.jpg"}}" alt=""></div>
                <div class="blog-content">
                    <div class="blog-name">
                        <h4>E-Business</h4>
                    </div>
                    <div class="content">
                        <p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum.</p>
                    </div>
                    <div class="blog-link">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Learn more" title="Learn more" template="widget/link/link_inline.phtml" page_id="1"}}</div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="blog-item">
                <div class="blog-image"><img src="{{media url="wysiwyg/homepage/main_homepage/blog/homepage-retail-12.jpg"}}" alt=""></div>
                <div class="blog-content">
                    <div class="blog-name">
                        <h4>Why buy from this site</h4>
                    </div>
                    <div class="content">
                        <p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum.</p>
                    </div>
                    <div class="blog-link">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Learn more" title="Learn more" template="widget/link/link_inline.phtml" page_id="1"}}</div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="blog-item">
                <div class="blog-image"><img src="{{media url="wysiwyg/homepage/main_homepage/blog/homepage-retail-12.jpg"}}" alt=""></div>
                <div class="blog-content">
                    <div class="blog-name">
                        <h4>Benefits of being our customer</h4>
                    </div>
                    <div class="content">
                        <p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum.</p>
                    </div>
                    <div class="blog-link">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Learn more" title="Learn more" template="widget/link/link_inline.phtml" page_id="1"}}</div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- popular_categries -->
<div class="popular-categries">
    <div class="content-heading">
        <h2 class="title">Popular categories</h2>
    </div>
    <div class="row">
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-white-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/dark-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/47"}}</div>
            </div>
        </div>
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-dark-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/white-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/43"}}</div>
            </div>
        </div>
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-dark-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/white-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/42"}}</div>
            </div>
        </div>
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-dark-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/white-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/46"}}</div>
            </div>
        </div>
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-dark-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/white-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/44"}}</div>
            </div>
        </div>
        <div class="col-2">
            <div class="categories">
                <div class="icon-image-dark-hat"><img src="{{media url=&quot;wysiwyg/homepage/main_homepage/icon_main_homepage/white-hat@2x.png&quot;}}" alt="" /></div>
                <div class="categories-links">{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/48"}}</div>
            </div>
        </div>
    </div>
</div>

<!-- featured_brands -->
<div class="featured-brands">
    <div class="content-heading">
        <h2 class="title">Featured brands</h2>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-10.jpg"}}" alt=""></div>
        </div>
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-9.jpg"}}" alt=""></div>
        </div>
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-8.jpg"}}" alt=""></div>
        </div>
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-7.jpg"}}" alt=""></div>
        </div>
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-6.jpg"}}" alt=""></div>
        </div>
        <div class="col-4">
            <div class="brands-image"><img src="{{media url="wysiwyg/homepage/main_homepage/brands/homepage-retail-5.jpg"}}" alt=""></div>
        </div>
    </div>
    <div class="brands-links">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="View all brands" title="View all brands" template="widget/link/link_block.phtml" page_id="1"}}</div>
</div>

<!-- services_solutions -->
<div class="services-solutions">
    <div class="content-heading">
        <h2 class="title">Services & solutions</h2>
    </div>
    <div class="solutions">
        <div class="solutions-image"><img src="{{media url="wysiwyg/homepage/main_homepage/solutions/homepage-lhs-shape@2x.png"}}" alt=""></div>
        <div class="solutions-content">
            <p class="list-text">Heatleys customised online ordering portal is the customers personalised electronic catalogue which allows access to contract pricing plus the ability to place orders.</p>
            <p class="node">(Please note this is for a set and agreed basket of goods only)</p>
            <div class="solutions-link">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="Learn more" title="Learn more" template="widget/link/link_block.phtml" page_id="1"}}</div>
        </div>
    </div>
</div>

<!-- news_heatleys -->
<div class="session-news-heatleys">
    <div class="content-heading">
        <h2 class="title">Heatley news</h2>
        <div class="links">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="View all" title="View all" template="widget/link/link_block.phtml" page_id="1"}}</div>
    </div>
    <div id="news-heatleys" class="news-blog">
        <div class="news-item">
            <div class="news-container">
                <div class="news-image"><img src="{{media url="wysiwyg/homepage/main_homepage/news/homepage-retail-4.jpg"}}" alt=""></div>
                <div class="news-content">
                    <div class="categories">Tools &amp; Skills</div>
                    <div class="name">
                        <h5>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="5 things to know before selecting a power tool" title="5 things to know before selecting a power tool" template="widget/link/link_inline.phtml" page_id="1"}}</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="news-item">
            <div class="news-container">
                <div class="news-image"><img src="{{media url="wysiwyg/homepage/main_homepage/news/homepage-retail-3.jpg"}}" alt=""></div>
                <div class="news-content">
                    <div class="categories">Tools &amp; Skills</div>
                    <div class="name">
                        <h5>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="5 things to know before selecting a power tool" title="5 things to know before selecting a power tool" template="widget/link/link_inline.phtml" page_id="1"}}</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="news-item">
            <div class="news-container">
                <div class="news-image"><img src="{{media url="wysiwyg/homepage/main_homepage/news/homepage-retail-2.jpg"}}" alt=""></div>
                <div class="news-content">
                    <div class="categories">Tools &amp; Skills</div>
                    <div class="name">
                        <h5>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="5 things to know before selecting a power tool" title="5 things to know before selecting a power tool" template="widget/link/link_inline.phtml" page_id="1"}}</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="news-item">
            <div class="news-container">
                <div class="news-image"><img src="{{media url="wysiwyg/homepage/main_homepage/news/homepage-retail-1.jpg"}}" alt=""></div>
                <div class="news-content">
                    <div class="categories">Tools &amp; Skills</div>
                    <div class="name">
                        <h5>{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="5 things to know before selecting a power tool" title="5 things to know before selecting a power tool" template="widget/link/link_inline.phtml" page_id="1"}}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>